### ISSUE TITLE
module Xlsxir.Index is not available

### ISSUE THREAD

**Issue by hopewise** [AlexKovalevych/exoffice#6]
I get this error:

```
** (UndefinedFunctionError) function Xlsxir.Index.new/0 is undefined (module Xlsxir.Index is not available)
    Xlsxir.Index.new()
    (exoffice) lib/exoffice/parser/excel_2003/loader.ex:66: Exoffice.Parser.Excel2003.Loader.get_stream/1
    (exoffice) lib/exoffice/parser/excel_2003/loader.ex:45: Exoffice.Parser.Excel2003.Loader.load/2
    (exoffice) lib/exoffice.ex:51: Exoffice.parse/2
```

Any idea?

**Comment by AlexKovalevych** [comment]
`xlsxir` library was updated, so i've added support for it in the latest master, will increment library version soon
